Fixing debian sshupdated-startup. Now all works.

diff --git a/deps/deb/startscript b/deps/deb/startscript
--- a/deps/deb/startscript
+++ b/deps/deb/startscript
@@ -1,235 +1,147 @@
-#!/bin/bash
-#
-# sshupdated		Start up the OpenSSH server daemon
-#
-# chkconfig: 2345 55 25
-# description: SSH is a protocol for secure remote shell access. \
-#              This service starts up the OpenSSH server daemon.
-#
-# processname: sshupdated
-# config: /etc/ssh/ssh_host_key
-# config: /etc/ssh/ssh_host_key.pub
-# config: /etc/ssh/ssh_random_seed
-# config: /etc/ssh/sshd_config
-# pidfile: /var/run/sshd.pid
+#!/bin/sh
 
 ### BEGIN INIT INFO
-# Provides: sshupdated
-# Required-Start: $local_fs $network $syslog
-# Required-Stop: $local_fs $syslog
-# Should-Start: $syslog
-# Should-Stop: $network $syslog
-# Default-Start: 2 3 4 5
-# Default-Stop: 0 1 6
-# Short-Description: OpenSSH server daemon for patching
-# Description:      SSHD configured for centralized patching
+# Provides:		sshupdated
+# Required-Start:	$remote_fs $syslog
+# Required-Stop:	$remote_fs $syslog
+# Default-Start:	2 3 4 5
+# Default-Stop:		0 1 6
+# Short-Description:	sshupdate daemon for patch management
 ### END INIT INFO
 
-# source function library
-. /etc/rc.d/init.d/functions
+set -e
 
-# pull in sysconfig settings
-[ -f /etc/sysconfig/sshd ] && . /etc/sysconfig/sshd
+# /etc/init.d/ssh: start and stop the OpenBSD "secure shell(tm)" daemon
 
-RETVAL=0
-prog="sshd"
-lockfile=/var/lock/subsys/sshupdated
+test -x /usr/sbin/sshd || exit 0
+( /usr/sbin/sshd -\? 2>&1 | grep -q OpenSSH ) 2>/dev/null || exit 0
 
-# Some functions to make the below more readable
-KEYGEN=/usr/bin/ssh-keygen
-SSHD=/usr/sbin/sshd
-SSHD_CONFIG=/etc/ssh/sshupdated.conf
-OPTIONS="-f $SSHD_CONFIG"
-RSA1_KEY=/etc/ssh/ssh_host_key
-RSA_KEY=/etc/ssh/ssh_host_rsa_key
-DSA_KEY=/etc/ssh/ssh_host_dsa_key
-PID_FILE=/var/run/sshupdated.pid
+umask 022
 
-runlevel=$(set -- $(runlevel); eval "echo \$$#" )
+if test -f /etc/default/sshupdated; then
+    . /etc/default/sshupdated
+fi
 
-fips_enabled() {
-	if [ -r /proc/sys/crypto/fips_enabled ]; then
-		cat /proc/sys/crypto/fips_enabled
-	else
-		echo 0
+. /lib/lsb/init-functions
+
+SSHUPDATE_CONF=/etc/ssh/sshupdated.conf
+
+if [ -n "$2" ]; then
+    SSHD_OPTS="$SSHD_OPTS $2"
+fi
+
+# Are we running from init?
+run_by_init() {
+    ([ "$previous" ] && [ "$runlevel" ]) || [ "$runlevel" = S ]
+}
+
+check_dev_null() {
+    if [ ! -c /dev/null ]; then
+	if [ "$1" = log_end_msg ]; then
+	    log_end_msg 1 || true
 	fi
-}
-
-do_rsa1_keygen() {
-	if [ ! -s $RSA1_KEY -a `fips_enabled` -eq 0 ]; then
-		echo -n $"Generating SSH1 RSA host key: "
-		rm -f $RSA1_KEY
-		if test ! -f $RSA1_KEY && $KEYGEN -q -t rsa1 -f $RSA1_KEY -C '' -N '' >&/dev/null; then
-			chmod 600 $RSA1_KEY
-			chmod 644 $RSA1_KEY.pub
-			if [ -x /sbin/restorecon ]; then
-			    /sbin/restorecon $RSA1_KEY.pub
-			fi
-			success $"RSA1 key generation"
-			echo
-		else
-			failure $"RSA1 key generation"
-			echo
-			exit 1
-		fi
+	if ! run_by_init; then
+	    log_action_msg "/dev/null is not a character device!" || true
 	fi
+	exit 1
+    fi
 }
 
-do_rsa_keygen() {
-	if [ ! -s $RSA_KEY ]; then
-		echo -n $"Generating SSH2 RSA host key: "
-		rm -f $RSA_KEY
-		if test ! -f $RSA_KEY && $KEYGEN -q -t rsa -f $RSA_KEY -C '' -N '' >&/dev/null; then
-			chmod 600 $RSA_KEY
-			chmod 644 $RSA_KEY.pub
-			if [ -x /sbin/restorecon ]; then
-			    /sbin/restorecon $RSA_KEY.pub
-			fi
-			success $"RSA key generation"
-			echo
-		else
-			failure $"RSA key generation"
-			echo
-			exit 1
-		fi
-	fi
+check_privsep_dir() {
+    # Create the PrivSep empty dir if necessary
+    if [ ! -d /var/run/sshd ]; then
+	mkdir /var/run/sshd
+	chmod 0755 /var/run/sshd
+    fi
 }
 
-do_dsa_keygen() {
-	if [ ! -s $DSA_KEY ]; then
-		echo -n $"Generating SSH2 DSA host key: "
-		rm -f $DSA_KEY
-		if test ! -f $DSA_KEY && $KEYGEN -q -t dsa -f $DSA_KEY -C '' -N '' >&/dev/null; then
-			chmod 600 $DSA_KEY
-			chmod 644 $DSA_KEY.pub
-			if [ -x /sbin/restorecon ]; then
-			    /sbin/restorecon $DSA_KEY.pub
-			fi
-			success $"DSA key generation"
-			echo
-		else
-			failure $"DSA key generation"
-			echo
-			exit 1
-		fi
-	fi
+check_config() {
+    if [ ! -e /etc/ssh/sshd_not_to_be_run ]; then
+	/usr/sbin/sshd $SSHD_OPTS -t || exit 1
+    fi
 }
 
-do_restart_sanity_check()
-{
-	$SSHD -t
-	RETVAL=$?
-	if [ $RETVAL -ne  0 ]; then
-		failure $"Configuration file or keys are invalid"
-		echo
-	fi
-}
-
-start()
-{
-	[ -x $SSHD ] || exit 5
-	[ -f $SSHD_CONFIG ] || exit 6
-	# Create keys if necessary
-	if [ "x${AUTOCREATE_SERVER_KEYS}" != xNO ]; then
-		do_rsa1_keygen
-		do_rsa_keygen
-		do_dsa_keygen
-	fi
-
-	echo -n $"Starting $prog: "
-	$SSHD $OPTIONS && success || failure
-	RETVAL=$?
-	[ $RETVAL -eq 0 ] && touch $lockfile
-	echo
-	return $RETVAL
-}
-
-stop()
-{
-	echo -n $"Stopping $prog: "
-	killproc -p $PID_FILE $SSHD
-	RETVAL=$?
-	# if we are in halt or reboot runlevel kill all running sessions
-	# so the TCP connections are closed cleanly
-	if [ "x$runlevel" = x0 -o "x$runlevel" = x6 ] ; then
-	    trap '' TERM
-	    killall $prog 2>/dev/null
-	    trap TERM
-	fi
-	[ $RETVAL -eq 0 ] && rm -f $lockfile
-	echo
-}
-
-reload()
-{
-	echo -n $"Reloading $prog: "
-	killproc -p $PID_FILE $SSHD -HUP
-	RETVAL=$?
-	echo
-}
-
-restart() {
-	stop
-	start
-}
-
-force_reload() {
-	restart
-}
-
-rh_status() {
-	status -p $PID_FILE openssh-daemon
-}
-
-rh_status_q() {
-	rh_status >/dev/null 2>&1
-}
+export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"
 
 case "$1" in
-	start)
-		rh_status_q && exit 0
-		start
-		;;
-	stop)
-		if ! rh_status_q; then
-			rm -f $lockfile
-			exit 0
+  start)
+	check_privsep_dir
+	check_dev_null
+	log_daemon_msg "Starting sshupdate - Using OpenBSD Secure Shell server" "sshupdated" || true
+	if start-stop-daemon --start --quiet --oknodo --pidfile /var/run/sshupdated.pid --exec /usr/sbin/sshd -- -f $SSHUPDATE_CONF $SSHD_OPTS; then
+	    log_end_msg 0 || true
+	else
+	    log_end_msg 1 || true
+	fi
+	;;
+  stop)
+	log_daemon_msg "Stopping OpenBSD Secure Shell server" "sshupdated" || true
+	if start-stop-daemon --stop --quiet --oknodo --pidfile /var/run/sshupdated.pid; then
+	    log_end_msg 0 || true
+	else
+	    log_end_msg 1 || true
+	fi
+	;;
+
+  reload|force-reload)
+	check_config
+	log_daemon_msg "Reloading OpenBSD Secure Shell server's configuration" "sshupdated" || true
+	if start-stop-daemon --stop --signal 1 --quiet --oknodo --pidfile /var/run/sshupdated.pid --exec /usr/sbin/sshd -- -f $SSHUPDATE_CONF ; then
+	    log_end_msg 0 || true
+	else
+	    log_end_msg 1 || true
+	fi
+	;;
+
+  restart)
+	check_privsep_dir
+	check_config
+	log_daemon_msg "Restarting OpenBSD Secure Shell server" "sshupdated" || true
+	start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile /var/run/sshupdated.pid
+	check_dev_null log_end_msg
+	if start-stop-daemon --start --quiet --oknodo --pidfile /var/run/sshupdated.pid --exec /usr/sbin/sshd -- -f $SSHUPDATE_CONF $SSHD_OPTS; then
+	    log_end_msg 0 || true
+	else
+	    log_end_msg 1 || true
+	fi
+	;;
+
+  try-restart)
+	check_privsep_dir
+	check_config
+	log_daemon_msg "Restarting OpenBSD Secure Shell server" "sshupdated" || true
+	RET=0
+	start-stop-daemon --stop --quiet --retry 30 --pidfile /var/run/sshupdated.pid || RET="$?"
+	case $RET in
+	    0)
+		# old daemon stopped
+		check_dev_null log_end_msg
+		if start-stop-daemon --start --quiet --oknodo --pidfile /var/run/sshupdated.pid --exec /usr/sbin/sshd -- -f $SSHUPDATE_CONF $SSHD_OPTS; then
+		    log_end_msg 0 || true
+		else
+		    log_end_msg 1 || true
 		fi
-		stop
 		;;
-	restart)
-		restart
+	    1)
+		# daemon not running
+		log_progress_msg "(not running)" || true
+		log_end_msg 0 || true
 		;;
-	reload)
-		rh_status_q || exit 7
-		reload
+	    *)
+		# failed to stop
+		log_progress_msg "(failed to stop)" || true
+		log_end_msg 1 || true
 		;;
-	force-reload)
-		force_reload
-		;;
-	condrestart|try-restart)
-		rh_status_q || exit 0
-		if [ -f $lockfile ] ; then
-			do_restart_sanity_check
-			if [ $RETVAL -eq 0 ] ; then
-				stop
-				# avoid race
-				sleep 3
-				start
-			else
-				RETVAL=6
-			fi
-		fi
-		;;
-	status)
-		rh_status
-		RETVAL=$?
-		if [ $RETVAL -eq 3 -a -f $lockfile ] ; then
-			RETVAL=2
-		fi
-		;;
-	*)
-		echo $"Usage: $0 {start|stop|restart|reload|force-reload|condrestart|try-restart|status}"
-		RETVAL=2
+	esac
+	;;
+
+  status)
+	status_of_proc -p /var/run/sshupdated.pid /usr/sbin/sshd sshupdated && exit 0 || exit $?
+	;;
+
+  *)
+	log_action_msg "Usage: /etc/init.d/ssh {start|stop|reload|force-reload|restart|try-restart|status}" || true
+	exit 1
 esac
-exit $RETVAL
+
+exit 0
