Fixing startscript for el6/fedora so it works under both platforms Making sure that rpm adds port to selinux

diff --git a/deps/el6/startscript b/deps/el6/startscript
--- a/deps/el6/startscript
+++ b/deps/el6/startscript
@@ -1,17 +1,13 @@
 #!/bin/bash
 #
-# sshupdated		Start up the OpenSSH server daemon
+# sshupdated		sshupdate daemon for patching using OpenSSH	
 #
 # chkconfig: 2345 55 25
-# description: SSH is a protocol for secure remote shell access. \
-#              This service starts up the OpenSSH server daemon.
+# description: sshupdate daemon is used for patching the system. \
+#              This service uses the OpenSSH server daemon.
 #
 # processname: sshupdated
-# config: /etc/ssh/ssh_host_key
-# config: /etc/ssh/ssh_host_key.pub
-# config: /etc/ssh/ssh_random_seed
-# config: /etc/ssh/sshd_config
-# pidfile: /var/run/sshd.pid
+# pidfile: /var/run/sshupdated.pid
 
 ### BEGIN INIT INFO
 # Provides: sshupdated
@@ -21,107 +17,41 @@
 # Should-Stop: $network $syslog
 # Default-Start: 2 3 4 5
 # Default-Stop: 0 1 6
-# Short-Description: OpenSSH server daemon for patching
-# Description:      SSHD configured for centralized patching
+# Short-Description: sshupdate daemon for patching using OpenSSH
+# Description:      sshupdate daemon for patching using OpenSSH
 ### END INIT INFO
 
-# source function library
-. /etc/rc.d/init.d/functions
-
 # pull in sysconfig settings
-[ -f /etc/sysconfig/sshd ] && . /etc/sysconfig/sshd
+[ -f /etc/sysconfig/sshupdated ] && . /etc/sysconfig/sshupdated
 
 RETVAL=0
-prog="sshd"
+prog="sshupdated"
 lockfile=/var/lock/subsys/sshupdated
 
 # Some functions to make the below more readable
-KEYGEN=/usr/bin/ssh-keygen
 SSHD=/usr/sbin/sshd
 SSHD_CONFIG=/etc/ssh/sshupdated.conf
 OPTIONS="-f $SSHD_CONFIG"
-RSA1_KEY=/etc/ssh/ssh_host_key
-RSA_KEY=/etc/ssh/ssh_host_rsa_key
-DSA_KEY=/etc/ssh/ssh_host_dsa_key
 PID_FILE=/var/run/sshupdated.pid
 
 runlevel=$(set -- $(runlevel); eval "echo \$$#" )
 
-fips_enabled() {
-	if [ -r /proc/sys/crypto/fips_enabled ]; then
-		cat /proc/sys/crypto/fips_enabled
-	else
-		echo 0
-	fi
+success()
+{
+  [ $? = 0 ] && echo "[ ok ]"
 }
 
-do_rsa1_keygen() {
-	if [ ! -s $RSA1_KEY -a `fips_enabled` -eq 0 ]; then
-		echo -n $"Generating SSH1 RSA host key: "
-		rm -f $RSA1_KEY
-		if test ! -f $RSA1_KEY && $KEYGEN -q -t rsa1 -f $RSA1_KEY -C '' -N '' >&/dev/null; then
-			chmod 600 $RSA1_KEY
-			chmod 644 $RSA1_KEY.pub
-			if [ -x /sbin/restorecon ]; then
-			    /sbin/restorecon $RSA1_KEY.pub
-			fi
-			success $"RSA1 key generation"
-			echo
-		else
-			failure $"RSA1 key generation"
-			echo
-			exit 1
-		fi
-	fi
-}
-
-do_rsa_keygen() {
-	if [ ! -s $RSA_KEY ]; then
-		echo -n $"Generating SSH2 RSA host key: "
-		rm -f $RSA_KEY
-		if test ! -f $RSA_KEY && $KEYGEN -q -t rsa -f $RSA_KEY -C '' -N '' >&/dev/null; then
-			chmod 600 $RSA_KEY
-			chmod 644 $RSA_KEY.pub
-			if [ -x /sbin/restorecon ]; then
-			    /sbin/restorecon $RSA_KEY.pub
-			fi
-			success $"RSA key generation"
-			echo
-		else
-			failure $"RSA key generation"
-			echo
-			exit 1
-		fi
-	fi
-}
-
-do_dsa_keygen() {
-	if [ ! -s $DSA_KEY ]; then
-		echo -n $"Generating SSH2 DSA host key: "
-		rm -f $DSA_KEY
-		if test ! -f $DSA_KEY && $KEYGEN -q -t dsa -f $DSA_KEY -C '' -N '' >&/dev/null; then
-			chmod 600 $DSA_KEY
-			chmod 644 $DSA_KEY.pub
-			if [ -x /sbin/restorecon ]; then
-			    /sbin/restorecon $DSA_KEY.pub
-			fi
-			success $"DSA key generation"
-			echo
-		else
-			failure $"DSA key generation"
-			echo
-			exit 1
-		fi
-	fi
+failure()
+{
+  [ $? = 0 ] || echo "[ fail ]"
 }
 
 do_restart_sanity_check()
 {
-	$SSHD -t
+	$SSHD -f $SSHD_CONFIG -t
 	RETVAL=$?
 	if [ $RETVAL -ne  0 ]; then
-		failure $"Configuration file or keys are invalid"
-		echo
+		echo "Configuration file or keys are invalid" ; exit 1
 	fi
 }
 
@@ -129,15 +59,10 @@ start()
 {
 	[ -x $SSHD ] || exit 5
 	[ -f $SSHD_CONFIG ] || exit 6
-	# Create keys if necessary
-	if [ "x${AUTOCREATE_SERVER_KEYS}" != xNO ]; then
-		do_rsa1_keygen
-		do_rsa_keygen
-		do_dsa_keygen
-	fi
 
 	echo -n $"Starting $prog: "
 	$SSHD $OPTIONS && success || failure
+        pgrep -f $SSHD_CONFIG > $PID_FILE
 	RETVAL=$?
 	[ $RETVAL -eq 0 ] && touch $lockfile
 	echo
@@ -147,7 +72,12 @@ start()
 stop()
 {
 	echo -n $"Stopping $prog: "
-	killproc -p $PID_FILE $SSHD
+        if [ -f "$PID_FILE" ]; then 
+          kill -9 $(cat $PID_FILE) && success || failure
+          [ $? = 0 ] && rm -f $PID_FILE
+        else
+          failure
+        fi
 	RETVAL=$?
 	# if we are in halt or reboot runlevel kill all running sessions
 	# so the TCP connections are closed cleanly
@@ -163,7 +93,7 @@ stop()
 reload()
 {
 	echo -n $"Reloading $prog: "
-	killproc -p $PID_FILE $SSHD -HUP
+        [ -f "$PID_FILE" ] && kill -HUP $(cat $PID_FILE)
 	RETVAL=$?
 	echo
 }
@@ -177,38 +107,27 @@ force_reload() {
 	restart
 }
 
-rh_status() {
-	status -p $PID_FILE openssh-daemon
-}
-
-rh_status_q() {
-	rh_status >/dev/null 2>&1
-}
-
 case "$1" in
 	start)
-		rh_status_q && exit 0
+		pgrep -f $SSHD_CONFIG > /dev/null 2>&1
+                [ $? = 0 ] && exit 1
 		start
 		;;
 	stop)
-		if ! rh_status_q; then
-			rm -f $lockfile
-			exit 0
-		fi
+		pgrep -f $SSHD_CONFIG > /dev/null 2>&1
+                [ $? = 0 ] || exit 0
 		stop
 		;;
 	restart)
 		restart
 		;;
 	reload)
-		rh_status_q || exit 7
 		reload
 		;;
 	force-reload)
 		force_reload
 		;;
 	condrestart|try-restart)
-		rh_status_q || exit 0
 		if [ -f $lockfile ] ; then
 			do_restart_sanity_check
 			if [ $RETVAL -eq 0 ] ; then
@@ -222,11 +141,8 @@ case "$1" in
 		fi
 		;;
 	status)
-		rh_status
-		RETVAL=$?
-		if [ $RETVAL -eq 3 -a -f $lockfile ] ; then
-			RETVAL=2
-		fi
+                echo -n $"Status of $prog: "
+		pgrep -f $SSHD_CONFIG > /dev/null 2>&1 && success || failure
 		;;
 	*)
 		echo $"Usage: $0 {start|stop|restart|reload|force-reload|condrestart|try-restart|status}"
